name: docs build

on:
  push:
    branches:
      # ç¡®ä¿è¿™æ˜¯ä½ æ­£åœ¨ä½¿ç”¨çš„åˆ†æ”¯åç§°
      - main

jobs:
  LearnData-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
        with:
          # è·å–æ‰€æœ‰æ ‡è®°å’Œåˆ†æ”¯çš„æ‰€æœ‰å†å²è®°å½•ï¼ˆupdatetime å¿…é¡»ï¼Œå¦åˆ™æ¯æ¬¡éƒ½ä¼šå˜åŒ–ï¼‰
          fetch-depth: 0
          # å¦‚æœä½ æ–‡æ¡£éœ€è¦ Git å­æ¨¡å—ï¼Œå–æ¶ˆæ³¨é‡Šä¸‹ä¸€è¡Œ
          # submodules: true

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      # å°†è¯»ä¹¦ç¬”è®°å¤åˆ¶åˆ°é™æ€é¡µè·¯å¾„ï¼Œç„¶åæ„å»ºé¡µé¢
      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run cpx "docs/reading/**" docs/.vuepress/public/reading
          npm run docs:build
          > docs/.vuepress/dist/.nojekyll

      # éƒ¨ç½²åˆ° GitHub Pages
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # è¿™æ˜¯æ–‡æ¡£éƒ¨ç½²åˆ°çš„åˆ†æ”¯åç§°
          branch: gh-pages
          folder: docs/.vuepress/dist

      # å°†é¡µé¢æ›´æ–°åˆ° Vercel
      - name: Copy file to Vercel
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: docs/.vuepress/dist

      - name: Deploy to Vercel
        uses: amondnet/upload-artifact-vercel-action@v1.0.1
        with:
          personal_token: ${{secrets.PERSONAL_TOKEN }}
          src_path: docs/.vuepress/dist
          build_timeout: 120000 # (default is 300000, 5 minutes)
          alias: my-vuepress-app # (default is generated by Vercel)
          # å¦‚æœä½ æƒ³å°† Vercel éƒ¨ç½²ä¸ Git å­˜å‚¨åº“é“¾æ¥èµ·æ¥ï¼Œè¯·å–æ¶ˆæ³¨é‡Šä¸‹é¢çš„å‚æ•°å¹¶è®¾ç½®æ­£ç¡®çš„å€¼ã€‚
          # repo_org: "<username>"
          # repo_name: "<repository-name>"
          # repo_branch: "<repository-branch>"
